steps:
    - name: gcr.io/k8s-skaffold/pack
      args:
        - build
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - '--builder=gcr.io/buildpacks/builder:v1'
        - '--path=.'
      id: Buildpack
      entrypoint: pack
    - name: gcr.io/cloud-builders/docker
      args:
        - push
        - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      id: Push
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      args:
        - run
        - services
        - update
        - $_SERVICE_NAME
        - '--platform=managed'
        - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
        - >-
          --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
        - '--region=$_DEPLOY_REGION'
        - '--quiet'
      id: Deploy
      entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _LABELS: gcb-trigger-id=70baf67c-3603-43b2-be07-8e6c94dab1b0
  _TRIGGER_ID: d70884a5-39f1-4b24-804b-b5c07e3e51bd
  _SERVICE_NAME: epoxi
  _DEPLOY_REGION: us-central1
  _GOOGLE_RUNTIME_VERSION
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - epoxi